// ignore_for_file: constant_identifier_names

/// LOGIN ENDPOINTS
/// * LOGIN_API_ENDPOINTS
/// ____
/// * VERIFY_API_TOKEN_ENDPOINTS
const String LOGIN_API_ENDPOINTS = "members/login",
    VERIFY_API_TOKEN_ENDPOINTS = "members/verify-token";

/// USER CONNECTIONS ENDPOINTS
/// * MY_CONNECTIONS_API_ENDPOINTS
/// ____
/// * MY_CONNECTORS_API_ENDPOINTS
const String MY_CONNECTIONS_API_ENDPOINTS =
        "members/user-connection-account/member",
    MY_CONNECTORS_API_ENDPOINTS = "members/user-connection-account/connection";

/// ATTENDANCE SCHEDULE ENDPOINTS
/// * ONE_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * MY_UPCOMMING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * MY_TODAY_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * MY_NOW_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * MY_DATE_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String ONE_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule",
    MY_UPCOMMING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/upcoming",
    MY_TODAY_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/today",
    MY_NOW_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/now",
    MY_DATE_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/date";

/// ATTENDANCE SCHEDULE DAYS/DATES ENDPOINTS
/// * DATES_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * DAYS_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String DATES_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/date",
    DAYS_ATTENDANCE_SCHEDULES_API_ENDPOINTS = "attendance/meeting-event/day";

/// ATTENDANCE SCHEDULE BREAK ENDPOINTS
/// * BREAK_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String BREAK_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
    "attendance/meeting-event/break";

/// ATTENDANCE SCHEDULE LOCATION ENDPOINTS
/// * LOCATION_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String LOCATION_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
    "attendance/meeting-event/location";

/// ATTENDANCE SCHEDULE MEETING PLACE ENDPOINTS
/// * MEETING_PLACE_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * VIRTUAL_MEETING_TYPE_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String MEETING_PLACE_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/locations",
    VIRTUAL_MEETING_TYPE_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/schedule/link-types";

/// MEMBER CLOCKING ATTENDANCE SCHEDULE ENDPOINTS
/// * CLOCK_IN_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * CLOCK_OUT_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * START_BREAK_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * END_BREAK_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * CANCEL_CLOCKING_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * BULK_CLOCKING_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
/// ____
/// * ATTENDANCE_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS
const String CLOCK_IN_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/clock-in",
    CLOCK_OUT_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/clock-out",
    START_BREAK_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/start-break",
    END_BREAK_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/end-break",
    CANCEL_CLOCKING_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/cancel-clocking",
    BULK_CLOCKING_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance/bulk-clocking",
    ATTENDANCE_MEMBER_CLOCKING_ATTENDANCE_SCHEDULES_API_ENDPOINTS =
        "attendance/meeting-event/attendance";

/// CLOCKING DEVICE ENDPOINTS
/// * CLOCKING_DEVICE_API_ENDPOINTS
/// ____
/// * CLOCKING_DEVICE_REQUEST_API_ENDPOINTS
const String CLOCKING_DEVICE_API_ENDPOINTS =
    "attendance/clocking-device/settings";
const String CLOCKING_DEVICE_REQUEST_API_ENDPOINTS =
    "attendance/clocking-device/request";
